export interface Acticity{
    approvedIssues:number,
    rejectedIssues:number,
    avgIssueAcionTime:number,
    issueAcceptanceRate:number,
    issueRejectionRate:number,
    avgIssueReviewTime:number,
    acceptedIssueRequests:number,
    rejectedIssueRequests:number,
    issueRequestAcceptRate:number,
    issueRequestRejectRate:number,
    acceptedIssueReviews:number,
    rejectedIssueReviews:number,
    issueReviewAcceptRate:number,
    issueReviewRejectRate:number,
    reviewAcceptedIssues:number,
} 
